### PR TITLE
Update Swift example

### PR DESCRIPTION
**Pull request by MacMeDan**
Update to Swift5
Add Swift Example
Add ChannelViewController and RoomViewController.
Add Support for muting a `TSUser`

### CODE REVIEW

**Comment by JanC** [comment]
I'm fine with dropping completely the Objective-C example app. Could you do it in this PR?

**Comment by MacMeDan** [comment]
Ya I could do that. Do you want to do that right now. There still is some features that are not implemented in the Swift example that are available in the Objective C one. Like `Fallowing` a `User` and the delegate is not being leveraged at all.

**Comment by MacMeDan** [comment]
So I would say it may be too early for that. I would leave it in and create some issues that outline features that could be added. I was using the ObjectiveC version as a road map for what would be added next.

**Comment by JanC** [comment]
ok, sounds good.

**Comment by MacMeDan** [comment]
But ya, as I replace parts I will delete them out.

**Comment by MacMeDan** [comment]
So do you want to merge this in?

**Pull request merged**
